### ISSUE TITLE
YYModel遇到问题

### ISSUE THREAD

**Issue by JohnnyHooo** [Xcoder1011/SKGenerateModelTool#2]
使用YYModel为基类的时候错误，
YYModel.h是头文件的引用，不是实际类，不要：YYModel

**Comment by Xcoder1011** [comment]
能贴一张图片，指明哪里有问题吗？

**Comment by sonwa** [comment]
我都遇到同样问题，楼主的意思应该是这样

#import "YYModel.h" 换成 #import <Foundation/Foundation.h>

YYModel 换成 NSObject

**Comment by sonwa** [comment]
就是不用判断YYModel就正常了。

![image](https://user-images.githubusercontent.com/1425134/148518767-3539abea-d985-4a9c-9977-3e253819c626.png)

**Comment by Xcoder1011** [comment]
Hello, 感谢提出问题，最新代码已经修复了这个问题。

**Comment by sonwa** [comment]
您好，我已经收到你刚刚发来的邮件，我会尽快回复！
The e-mail you sent to me has been received,I will check it as soon as possible,thank you.这一封邮件是系统自动回复。This e-mail is automatically reply.

**Comment by Xcoder1011** [comment]
> 使用YYModel为基类的时候错误， YYModel.h是头文件的引用，不是实际类，不要：YYModel



> 就是不用判断YYModel就正常了。
> 
> ![image](https://user-images.githubusercontent.com/1425134/148518767-3539abea-d985-4a9c-9977-3e253819c626.png)

是的，感谢指出。
